version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: taw_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: taw_backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://db:27017/taw_overseas
    depends_on:
      - db

volumes:
  mongo_data:
